steps:
- pwsh: |
    $ErrorActionPreference = 'Stop'
    $VerbosePreference = 'Continue'
    Set-StrictMode -Version Latest
    Import-Module .\build\PSRepositoryReleaseManager\src\PSRepositoryReleaseManager\PSRepositoryReleaseManager.psm1
    Import-Module .\build\PSRepositoryReleaseManager\lib\PSGitHubRestApi\src\PSGitHubRestApi\PSGitHubRestApi.psm1
    $releaseBody = .\build\PSRepositoryReleaseManager\src\scripts\Generate-RepositoryReleaseBody.ps1 -Path $(Get-Location) -TagName $env:RELEASE_TAG_REF
    .\build\PSRepositoryReleaseManager\src\scripts\Create-GitHubRelease.ps1 -Namespace $env:RELEASE_NAMESPACE -Repository $env:RELEASE_REPOSITORY -TagName $env:RELEASE_TAG_REF -ReleaseBody $releaseBody -ApiKey $env:GITHUB_API_TOKEN > $null
  displayName: Create GitHub release
  condition: and(startsWith(variables['Build.SourceBranch'], 'refs/tags/'), ne(variables['RELEASE_TAG_REF'], ''))
  env:
    GITHUB_API_TOKEN: $(GITHUB_API_TOKEN)
