steps:
- pwsh: |
    $ErrorActionPreference = 'Stop'
    $VerbosePreference = 'Continue'
    Set-StrictMode -Version Latest
    Import-Module .\build\PSRepositoryReleaseManager\src\PSRepositoryReleaseManager\PSRepositoryReleaseManager.psm1
    Import-Module .\build\PSRepositoryReleaseManager\lib\PSGitHubRestApi\src\PSGitHubRestApi\PSGitHubRestApi.psm1
    $private:generateArgs = @{
        Path = "$(Get-Location)"
        TagName = $env:RELEASE_TAG_REF
        Variant = 'DateCommitHistory'
        ReleaseNotesPath = if ($env:RELEASE_NOTES_PATH) { $env:RELEASE_NOTES_PATH } else { "$(git rev-parse --show-toplevel)\.release-notes.md" }
    }
    Get-RepositoryReleaseNotes @generateArgs
  displayName: Generate release notes
  condition: and(startsWith(variables['Build.SourceBranch'], 'refs/tags/'), ne(variables['RELEASE_TAG_REF'], ''))
