steps:
- pwsh: |
    .\build\PSRepositoryReleaseManager\src\scripts\ci\Generate-ReleaseNotes.ps1
  displayName: Generate release notes
  condition: and(startsWith(variables['Build.SourceBranch'], 'refs/tags/'), ne(variables['RELEASE_TAG_REF'], ''))
