parameters:
  RELEASE_NOTES_VARIANT: ''
  RELEASE_NOTES_PATH: ''

steps:
- powershell: |
    $ErrorActionPreference = 'Stop'
    $ErrorView = 'NormalView'
    ### Begin CI-specific code: Get the namspace, project name, and tag ref
    $matchInfo = $env:BUILD_SOURCEBRANCH | Select-String -Pattern '^refs\/tags\/(.*)'
    $env:RELEASE_TAG_REF = if ($matchInfo) { $matchInfo.Matches.Groups[1].Value } else { $null }
    $matchInfo = $env:BUILD_REPOSITORY_URI | Select-String -Pattern '^https:\/\/github.com\/(.*?)\/(.*)'
    $env:RELEASE_NAMESPACE = if ($matchInfo) { $matchInfo.Matches.Groups[1].Value } else { $null }
    $env:RELEASE_REPOSITORY = if ($matchInfo) { $matchInfo.Matches.Groups[2].Value } else { $null }
    ### End of CI-specific code
    "Namespace: '$env:RELEASE_NAMESPACE'" | Write-Host
    "Repository: '$env:RELEASE_REPOSITORY'" | Write-Host
    "Tag ref: '$env:RELEASE_TAG_REF'" | Write-Host
    $VerbosePreference = 'Continue'
    $releaseNotesPath = .\build\PSRepositoryReleaseManager\src\scripts\ci\Invoke-Generate.ps1
    Get-Content -Path $releaseNotesPath
    ### Begin CI-specific code: Set job-scoped variables
    echo "##vso[task.setvariable variable=RELEASE_NOTES_PATH_RESOLVED]${releaseNotesPath}"
    ### End of CI-specific code
  displayName: Generate release notes
  env:
    RELEASE_NOTES_VARIANT: ${{ parameters['RELEASE_NOTES_VARIANT'] }}
    RELEASE_NOTES_PATH: ${{ parameters['RELEASE_NOTES_PATH'] }}
- publish: '$(RELEASE_NOTES_PATH_RESOLVED)'
  displayName: Upload artifacts
  artifact: release-notes
