steps:
- powershell: |
    $ErrorActionPreference = 'Stop'
    $VerbosePreference = 'Continue'
    .\build\PSRepositoryReleaseManager\src\scripts\ci\Create-GitHubRelease.ps1 > $null
  displayName: Create GitHub release
  condition: and(startsWith(variables['Build.SourceBranch'], 'refs/tags/'), ne(variables['RELEASE_TAG_REF'], ''))
  env:
    GITHUB_API_TOKEN: $(GITHUB_API_TOKEN)
