steps:
- checkout: self
  submodules: recursive
- template: templates/azure-pipelines/entrypoint/release.yml@PSRepositoryReleaseManager
  # parameters:
  #   NAME: My release name
  #   NOTES_PATH: path/to/my-release-notes.md
  #   NOTES_CONTENT: |
  #     My
  #     multi-line
  #     release
  #     notes
  #   DRAFT: false
  #   PRERELEASE: false
  #   ASSETS: |
  #     path/to/asset1.tar.gz
  #     path/to/asset2.gz
  #     path/to/asset3.zip
  #     path/to/assets/*.gz
  #     path/to/assets/*.zip
