steps:
- checkout: self
  submodules: recursive
- template: templates/azure-pipelines/entrypoint/generate.yml@PSRepositoryReleaseManager
  # parameters:
  #   RELEASE_NOTES_VARIANT: VersionDate-HashSubject-NoMerges
  #   RELEASE_NOTES_PATH: path/to/my-release-notes.md
