steps:
- checkout: self
  submodules: recursive
- template: templates/azure-pipelines/entrypoint/generate.yml@PSRepositoryReleaseManager
  parameters:
    NOTES_PATH: path/to/my-release-notes.md
    VARIANT: DateHistory-HashSubject-NoMerges
