parameters:
  VARIANT: ''
  NOTES_PATH: ''

steps:
- pwsh: |
    $ErrorActionPreference = 'Stop'
    $ErrorView = 'NormalView'
    ### Begin CI-specific code: Get the namspace, project name, and tag ref
    $matchInfo = $env:BUILD_SOURCEBRANCH | Select-String -Pattern '^refs\/tags\/(.*)'
    $env:RELEASE_TAG_REF = if ($matchInfo) { $matchInfo.Matches.Groups[1].Value } else { $null }
    $matchInfo = $env:BUILD_REPOSITORY_URI | Select-String -Pattern '^https:\/\/github.com\/(.*?)\/(.*)'
    $env:RELEASE_NAMESPACE = if ($matchInfo) { $matchInfo.Matches.Groups[1].Value } else { $null }
    $env:RELEASE_REPOSITORY = if ($matchInfo) { $matchInfo.Matches.Groups[2].Value } else { $null }
    ### End of CI-specific code
    "Namespace: '$env:RELEASE_NAMESPACE'" | Write-Host
    "Repository: '$env:RELEASE_REPOSITORY'" | Write-Host
    "Tag ref: '$env:RELEASE_TAG_REF'" | Write-Host
    $VerbosePreference = 'Continue'
    $private:generateArgs = @{ ReleaseTagRef = $env:RELEASE_TAG_REF }
    if ($env:RELEASE_NOTES_VARIANT) { $private:generateArgs['ReleaseNotesVariant'] = $env:RELEASE_NOTES_VARIANT }
    if ($env:RELEASE_NOTES_PATH) { $private:generateArgs['ReleaseNotesPath'] = $env:RELEASE_NOTES_PATH }
    .\build\PSRepositoryReleaseManager\src\scripts\ci\Invoke-Generate.ps1 @private:generateArgs
  displayName: Generate release notes
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
  env:
    RELEASE_NOTES_VARIANT: ${{ parameters['VARIANT'] }}
    RELEASE_NOTES_PATH: ${{ parameters['NOTES_PATH'] }}
